### ISSUE TITLE
"Issue ベースの開発" レビュー依頼

### ISSUE THREAD

**Issue by tohohosan** [tohohosan/MuseUP#60]
■Webアプリの概要
ミュージアム（博物館・美術館等）を検索したり、投稿したりして、もっとミュージアムを知る・楽しむことができるサービスです。

ミュージアムを探す…
場所やカテゴリーから、ミュージアムを検索することができます。ミュージアムの説明やレビューを閲覧して興味を持ったミュージアムは、「行きたい」リストに入れることで、休日の行先の候補になるでしょう。

ミュージアムをオススメする…
自分が行ったことのあるミュージアムを投稿することもできます。さらにレビューを投稿することで、他のユーザーに自分の推しミュージアムをオススメすることもできます。

ミュージアムを楽しむ…
ミュージアムを「行った」リストや新規作成した独自のリストにまとめて管理したり、ミュージアムに対するプライベートなメモを残しておけます。

■1週間辺りの開発に向けられる時間

10/21~11/3 まで
- 1週間あたり： 15時間

11/4~12/8 まで
- 1週間あたり： 30時間

■ProjectsのURL
https://github.com/users/tohohosan/projects/1/views/1

■MVPリリースまで
- [ ] rails new
- [ ] Render.com にデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ミュージアム一覧機能
- [ ] ミュージアム投稿機能
- [ ] ミュージアム詳細表示機能
- [ ] ミュージアム検索機能
- [ ] レビュー機能
- [ ] リスト機能
- [ ] メモ機能

■MVP後
- [ ] SNSログイン（Googleログイン、Xログイン）
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] 運営からのお知らせ
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] ファビコン
- [ ] 独自ドメイン
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024 年 12 月 7 日

**Comment by ippei-shimizu** [comment]
概ね良いかと思います。LGTMです。
